language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
branches:
  only:
  - master
script:
- npm install
- npm test
cache:
  directories:
  - node_modules
notifications:
  email:
  - latchkey@gmail.com
env:
  global:
  - secure: gNhxEi/IH4KP1l8+MfMDCHzy7yzhAPT87yyFiV9Gy2pxi8F/3SDefSYddg2ohnJ1y1jAuhj22fCqQi+KAX485b52BB+kbk9kxET8zqCXk1OczCjxnpZQ2louMrUMT3+6tf1v0+wrkwmwzLniCyRHbrAkotOXSQu8PBskp9YYfvk=
before_install:
- npm install jspm
- jspm config endpoints.github.handler jspm-github
- jspm config endpoints.github.remote https://github.jspm.io
- jspm config endpoints.github.timeouts.lookups 60
- jspm config endpoints.github.maxRepoSize 0
- jspm config endpoints.github.auth $GH_TOKEN
- cat ~/.jspm/config
