language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- 'iojs'
branches:
  only:
  - master
script:
- npm install
- npm test
cache:
  directories:
  - node_modules
notifications:
  email:
  - latchkey@gmail.com
env:
  global:
  - secure: Dm2z7xuOcqK+KauO6lQVyKaHgCEX0bjS6mCbwFofETa5XQABQIuy9iS9z56LxmPlw4cor12FvxCArNLmKFNnwOCd5JZ+C2qTKaDLPNWsIHL0B49AIFL6RBHAJ7htAdCH00t/Jp1JHKjcBEl1srQKPV7CZwDQlIHHzPwC4ll3GQ4=
before_install:
- npm install jspm
- jspm config endpoints.github.auth $GH_TOKEN
