language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
branches:
  only:
  - master
addons:
  sauce_connect:
    username: latchkey
    access_key: $SAUCELABS_KEY
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./.travis.chrome.sh
- npm install jspm
- jspm config endpoints.github.auth $GH_TOKEN
install:
- npm install
script:
- npm test
- gulp run &
- npm run-script protractor-setup
- sleep 10
- npm run-script protractor-run
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email:
  - latchkey@gmail.com
env:
  global:
  - secure: Dm2z7xuOcqK+KauO6lQVyKaHgCEX0bjS6mCbwFofETa5XQABQIuy9iS9z56LxmPlw4cor12FvxCArNLmKFNnwOCd5JZ+C2qTKaDLPNWsIHL0B49AIFL6RBHAJ7htAdCH00t/Jp1JHKjcBEl1srQKPV7CZwDQlIHHzPwC4ll3GQ4=
