language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
branches:
  only:
  - master
script:
- npm install
- npm test
cache:
  directories:
  - node_modules
notifications:
  email:
  - latchkey@gmail.com
env:
  global:
  - secure: gCC6rNDXTa1SBJCyvzZC9pzJwab8iXdFDezqFnbUcMNWAl+nCeDCrGbxIFuM26Oud4jODku8BQNNp/nI0onbukoLCBe8iJ/GoweZeTsK+S1tuOi8lGg/89kZEsg5xAQ8LFXSSFJjmZzRQlOwgM6OvOxFmFPMLY9o5Ho67U1e/1Q=
before_install:
- npm install -g jspm
- jspm config endpoints.github.auth $GH_TOKEN
